name: React_node.yml

on:
  pull_request:
    branches: [ dev ]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  
jobs:
  build:
   # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install 

    #- name: Run the tests
     # run: npm test

    - name: Build
      run: npm run build
      env:
          CI: ""
    - name: Generate deployment package
      run: zip -r ${{ PR_NUMBER }}.zip ./build/*

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "${{ PR_NUMBER }}.zip"
          target: "/home/ec2-user/"

  deploy:
    needs: build
    runs-on: ubuntu-latest    

 # Secrets to be created in repository  Secret & Hostname & Username      
    steps:
      - name: ls -a via ssh
        uses: nerd4ever/ssh-action@master
        with:
          command: |
            cd /home/ec2-user/
            mkdir ${{ PR_NUMBER }}
            mv ${{ PR_NUMBER }}.zip ${{ PR_NUMBER }}
            cd ${{ PR_NUMBER }}
            unzip ${{ PR_NUMBER }}.zip
            
          host: ${{ secrets.HOSTNAME }}}
          user: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          

            



